### ISSUE TITLE
Montgomery squaring

### ISSUE THREAD

**Issue by jon-chuang** [ConsenSys/goff#11]
Hi, is the Montgomery squaring formula given in 
https://hackmd.io/@zkteam/modular_multiplication
accurate?  I can't seem to get it to work correctly.

**Comment by gbotrel** [comment]
Yes, the formula is correct (and is implemented in `goff`). Note that, as indicated in the article, it works only when the last  (most significant) word of the modulus meet the condition described here: https://hackmd.io/@zkteam/modular_multiplication#Montgomery-squaring

**Comment by mratsim** [comment]
It's correct. I tried to read the goff template but I couldn't understand why it was so complex though:

 https://github.com/ConsenSys/goff/blob/e44c99d099af8be17f0f8803d5cfc7ca56745334/cmd/internal/template/element/square.go#L16-L83

I've implemented it in Nim as a 1-to-1 translation of the algorithm which might be more readable at https://github.com/mratsim/constantine/blob/e47159e4/constantine/arithmetic/limbs_montgomery.nim#L169-L205

```Nim
func montySquare_CIOS_nocarry(r: var Limbs, a, M: Limbs, m0ninv: BaseType) =
  ## Montgomery Multiplication using Coarse Grained Operand Scanning (CIOS)
  ## and no-carry optimization.
  ## This requires the most significant word of the Modulus
  ##   M[^1] < high(Word) shr 2 (i.e. less than 0b00111...1111)
  ## https://hackmd.io/@zkteam/modular_multiplication

  # We want all the computation to be kept in registers
  # hence we use a temporary `t`, hoping that the compiler does it.
  var t: typeof(M) # zero-init
  const N = t.len
  staticFor i, 0, N:
    # Squaring
    var
      A1: Carry
      A0: Word
    # (A0, t[i]) <- a[i] * a[i] + t[i]
    muladd1(A0, t[i], a[i], a[i], t[i])
    staticFor j, i+1, N:
      # (A1, A0, t[j]) <- 2*a[j]*a[i] + t[j] + (A1, A0)
      # 2*a[j]*a[i] can spill 1-bit on a 3rd word
      mulDoubleAdd2(A1, A0, t[j], a[j], a[i], t[j], A1, A0)

    # Reduction
    #  m        <- (t[0] * m0ninv) mod 2^w
    # (C, _)    <- m * M[0] + t[0]
    let m = t[0] * Word(m0ninv)
    var C, lo: Word
    muladd1(C, lo, m, M[0], t[0])
    staticFor j, 1, N:
      # (C, t[j-1]) <- m*M[j] + t[j] + C
      muladd2(C, t[j-1], m, M[j], t[j], C)

    t[N-1] = C + A0

  discard t.csub(M, not(t < M))
  r = t
```

**Comment by gbotrel** [comment]
@mratsim I wish we didn't need to generate code / had a cleaner way to do it like your Nim snippet :-) 
Template is a bit longer than pseudo code as treating first iteration and last one in the inner loop saves few nano seconds.

**Comment by jon-chuang** [comment]
@gbotrel I find that surprising. For our case, there was no measurable difference in doing so. I believe the rust compiler is more confident in making certain optimisations, hence we could leave things in a more compact readable form.

**Comment by gbotrel** [comment]
I suspect it's coming from the fact that the  `bits.Mul64` or `bits.Add64` are constant time, even if inputs are 0.
