### ISSUE TITLE
Benchmark suggestions

### ISSUE THREAD

**Issue by mratsim** [ConsenSys/goff#6]
Regarding benchmarks here are some suggestions:

1. Reporting the CPU used and its clock frequency
2. Report the number of cycles required per op. This can be done with RDTSC instruction, I expect Go to offer an equivalent. Note that it's imprecise if the CPU is overclocked, uses turboboost or dynamic frequency scaling (the last 2 can be workaround by warming up the CPU before actual bench).
3. Benchmark vs Herumi's [mcl](https://github.com/herumi/mcl). It is currently the fastest public pairing library ([ate-pairing](https://github.com/herumi/ate-pairing) is slightly faster but developed anymore, in particular it doesn't support BLS curves) and several projects switched to it for signatures and zero-knowledge. On my CPU (i9-9980XE overclocked at 4.1GHz) it takes ~32 ns vs ~45 ns for Goff (clocks are wildly inaccurate for overclocked CPUs) on BLS12_381.
4. Benchmark vs [Miracl/core](https://github.com/miracl/core) or [Apache Milagro](https://github.com/apache/incubator-milagro-crypto-c), those are pairing libraries written by cryptographers and quite popular in Ethereum 2. You can retrieve generated C sources for BLS here: https://github.com/status-im/nim-blscurve/tree/9a143350/blscurve/csources/64
5. Benchmark vs [Fiat-Crypto](https://github.com/mit-plv/fiat-crypto), Fiat-Crypto is a formally verified elliptic curve and field arithmetic code generator in Coq. From a Coq description, C, Rust or Go code can be generated that has been formally verified.
6. Benchmark vs [HACL-Star](https://github.com/project-everest/hacl-star), similarly, HACL-Star is a formally verified cryptographic primitives code generator written in F*

**Comment by gbotrel** [comment]
Thanks for your comments;
1. The write up do mention the CPU and its clock frequency before the benchmark section:
```
All benchmarks hereafter are run on a 2016 MBP with a Intel Core i7 (2.9 GHz).
These results may be impacted by
available instruction set
CPU cache configuration
artifacts (thermal trottling, turbo boost, …)
compiler optimizations
```

2. We did experiment with that, although it doesn't appear very reliable in Go. We used [this package](https://github.com/dterei/gotsc) and results were too inconsistent. Using the Go `time` package was more accurate across platforms -- we didn't dig too much here, if you (or anybody reading this thread :-)) happen to know solid ways to use RDTSC in Go, we are extremely interested. Disabling garbage collection (`debug.SetGCPercent(-1)`) didn't help.

3. Do you mind sharing a quick gist on the code you used for `mcl`? I did play with `rawbench.cpp` and added `#define CYBOZU_BENCH_USE_GETTIMEOFDAY` (may not be an accurate way to measure), and on my CPU (core i7 2.9Ghz), the fastest results for `mcl` are for 4 words moduli `llvm_mont` (~25.10ns) and for 6 words moduli (bls381) `xbyak` (~52.60ns). Which is very comparable to `goff` `MulAssign` bench. Could also be that available instruction sets (like `ADCX` / parallel carry chains) differs, and `mcl` leverages that better than the Go compiler intrinsic does. [Go parenthesis: Go projects that need fast field arithmetics, unless I'm mistaken would need to use `mcl` through `cgo`,  which comes with a significant cost]

4., 5., 6. - Wasn't aware of 5 and 6, thanks for the pointers! . Properly and fairly benchmarking these various libraries on multiple environments would be great indeed, but likely not on our short-term roadmap. May create a github issue and reference yours though.

**Comment by mratsim** [comment]
Didn't see the MBP + core i7 note, thanks.

Fiat-crypto should be fairly easy, it generates self-contained curve files like goff, see: https://github.com/mit-plv/fiat-crypto/tree/master/fiat-go/src

For mcl this is what I do:

```bash
git clone git://github.com/herumi/mcl
cd mcl
make -j${ncpu} MCL_USE_GMP=0 bin/bls12_test.exe
bin/bls12_test.exe
```
(The .exe is valid also on Linux)

For convenience you might want to:
- always display time instead of clock cycles: edit here - https://github.com/herumi/mcl/blob/9b43a872/include/cybozu/benchmark.hpp#L18-L29
- comment out benches on Fp2+ and elliptic curve and pairing
  - comment out here: https://github.com/herumi/mcl/blob/9b43a872/test/bench.hpp#L60-L92
  - and: https://github.com/herumi/mcl/blob/9b43a872/test/bls12_test.cpp#L327-L336 (only keeping testBench()
  - and: https://github.com/herumi/mcl/blob/9b43a872c647144bb9a64ac0b0c860183b7df41b/test/bls12_test.cpp#L346-L383
  - and everything else that you do not want (miller loop, final exp, pairing take some time)

**Comment by mratsim** [comment]
The relic team has a fiat-crypto code for BLS12_381: https://github.com/relic-toolkit/relic/blob/5cdabd57/src/low/x64-fiat-381/bls12_381_q_64.c

Benched it on my computer, it's about 79 ns for Mul with Clang while Goff is 45 ns (https://github.com/mit-plv/fiat-crypto/issues/691)
