### ISSUE TITLE
Writeup: inverse or negative inverse?

### ISSUE THREAD

**Issue by mratsim** [ConsenSys/goff#7]
In the write-up it is mentioned that q' is the inverse of the field modulus mod R.

![image](https://user-images.githubusercontent.com/22738317/76150797-6eefb280-60ae-11ea-9a2a-8b83221b5bf5.png)

I believe it's the negative inverse `-q^-1 (mod R)` instead
![image](https://user-images.githubusercontent.com/22738317/76150813-9a729d00-60ae-11ea-833b-cc301c6513b7.png)
![image](https://user-images.githubusercontent.com/22738317/76150819-9fcfe780-60ae-11ea-86bf-fd83f3d7937b.png)

**Comment by gbotrel** [comment]
Correct, thanks for reporting
